apiVersion: v2
name: bindery-external-runtime
description: Bindery external-runtime control-plane reference service
type: application
version: 0.2.0
appVersion: 0.2.0
home: https://github.com/bayleafwalker/bindery-core
sources:
  - https://github.com/bayleafwalker/bindery-core

