// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.1
// source: proto/game/engine/v1/engine.proto

// Core engine RPC contract.
//
// Versioning:
// - Package name includes the major API version: game.engine.v1
// - Fields are assigned once and never reused.
// - New fields should use new numbers; deprecated fields should be reserved.

package enginev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	EngineModule_InitializeWorld_FullMethodName  = "/game.engine.v1.EngineModule/InitializeWorld"
	EngineModule_ApplyCommand_FullMethodName     = "/game.engine.v1.EngineModule/ApplyCommand"
	EngineModule_Tick_FullMethodName             = "/game.engine.v1.EngineModule/Tick"
	EngineModule_GetStateSnapshot_FullMethodName = "/game.engine.v1.EngineModule/GetStateSnapshot"
)

// EngineModuleClient is the client API for EngineModule service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// EngineModule defines the minimal RPC surface area required for a generic
// game engine module.
type EngineModuleClient interface {
	// InitializeWorld creates or resets engine-managed state for a world.
	InitializeWorld(ctx context.Context, in *InitializeWorldRequest, opts ...grpc.CallOption) (*InitializeWorldResponse, error)
	// ApplyCommand applies a player/system command. Commands are generic and
	// extensible via oneof.
	ApplyCommand(ctx context.Context, in *ApplyCommandRequest, opts ...grpc.CallOption) (*ApplyCommandResponse, error)
	// Tick advances the simulation.
	Tick(ctx context.Context, in *TickRequest, opts ...grpc.CallOption) (*TickResponse, error)
	// GetStateSnapshot returns a point-in-time snapshot of world state.
	GetStateSnapshot(ctx context.Context, in *GetStateSnapshotRequest, opts ...grpc.CallOption) (*GetStateSnapshotResponse, error)
}

type engineModuleClient struct {
	cc grpc.ClientConnInterface
}

func NewEngineModuleClient(cc grpc.ClientConnInterface) EngineModuleClient {
	return &engineModuleClient{cc}
}

func (c *engineModuleClient) InitializeWorld(ctx context.Context, in *InitializeWorldRequest, opts ...grpc.CallOption) (*InitializeWorldResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InitializeWorldResponse)
	err := c.cc.Invoke(ctx, EngineModule_InitializeWorld_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *engineModuleClient) ApplyCommand(ctx context.Context, in *ApplyCommandRequest, opts ...grpc.CallOption) (*ApplyCommandResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApplyCommandResponse)
	err := c.cc.Invoke(ctx, EngineModule_ApplyCommand_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *engineModuleClient) Tick(ctx context.Context, in *TickRequest, opts ...grpc.CallOption) (*TickResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TickResponse)
	err := c.cc.Invoke(ctx, EngineModule_Tick_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *engineModuleClient) GetStateSnapshot(ctx context.Context, in *GetStateSnapshotRequest, opts ...grpc.CallOption) (*GetStateSnapshotResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetStateSnapshotResponse)
	err := c.cc.Invoke(ctx, EngineModule_GetStateSnapshot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EngineModuleServer is the server API for EngineModule service.
// All implementations must embed UnimplementedEngineModuleServer
// for forward compatibility.
//
// EngineModule defines the minimal RPC surface area required for a generic
// game engine module.
type EngineModuleServer interface {
	// InitializeWorld creates or resets engine-managed state for a world.
	InitializeWorld(context.Context, *InitializeWorldRequest) (*InitializeWorldResponse, error)
	// ApplyCommand applies a player/system command. Commands are generic and
	// extensible via oneof.
	ApplyCommand(context.Context, *ApplyCommandRequest) (*ApplyCommandResponse, error)
	// Tick advances the simulation.
	Tick(context.Context, *TickRequest) (*TickResponse, error)
	// GetStateSnapshot returns a point-in-time snapshot of world state.
	GetStateSnapshot(context.Context, *GetStateSnapshotRequest) (*GetStateSnapshotResponse, error)
	mustEmbedUnimplementedEngineModuleServer()
}

// UnimplementedEngineModuleServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedEngineModuleServer struct{}

func (UnimplementedEngineModuleServer) InitializeWorld(context.Context, *InitializeWorldRequest) (*InitializeWorldResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InitializeWorld not implemented")
}
func (UnimplementedEngineModuleServer) ApplyCommand(context.Context, *ApplyCommandRequest) (*ApplyCommandResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ApplyCommand not implemented")
}
func (UnimplementedEngineModuleServer) Tick(context.Context, *TickRequest) (*TickResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Tick not implemented")
}
func (UnimplementedEngineModuleServer) GetStateSnapshot(context.Context, *GetStateSnapshotRequest) (*GetStateSnapshotResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStateSnapshot not implemented")
}
func (UnimplementedEngineModuleServer) mustEmbedUnimplementedEngineModuleServer() {}
func (UnimplementedEngineModuleServer) testEmbeddedByValue()                      {}

// UnsafeEngineModuleServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EngineModuleServer will
// result in compilation errors.
type UnsafeEngineModuleServer interface {
	mustEmbedUnimplementedEngineModuleServer()
}

func RegisterEngineModuleServer(s grpc.ServiceRegistrar, srv EngineModuleServer) {
	// If the following call pancis, it indicates UnimplementedEngineModuleServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&EngineModule_ServiceDesc, srv)
}

func _EngineModule_InitializeWorld_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InitializeWorldRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EngineModuleServer).InitializeWorld(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EngineModule_InitializeWorld_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EngineModuleServer).InitializeWorld(ctx, req.(*InitializeWorldRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EngineModule_ApplyCommand_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApplyCommandRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EngineModuleServer).ApplyCommand(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EngineModule_ApplyCommand_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EngineModuleServer).ApplyCommand(ctx, req.(*ApplyCommandRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EngineModule_Tick_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TickRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EngineModuleServer).Tick(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EngineModule_Tick_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EngineModuleServer).Tick(ctx, req.(*TickRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EngineModule_GetStateSnapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStateSnapshotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EngineModuleServer).GetStateSnapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EngineModule_GetStateSnapshot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EngineModuleServer).GetStateSnapshot(ctx, req.(*GetStateSnapshotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// EngineModule_ServiceDesc is the grpc.ServiceDesc for EngineModule service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EngineModule_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "game.engine.v1.EngineModule",
	HandlerType: (*EngineModuleServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "InitializeWorld",
			Handler:    _EngineModule_InitializeWorld_Handler,
		},
		{
			MethodName: "ApplyCommand",
			Handler:    _EngineModule_ApplyCommand_Handler,
		},
		{
			MethodName: "Tick",
			Handler:    _EngineModule_Tick_Handler,
		},
		{
			MethodName: "GetStateSnapshot",
			Handler:    _EngineModule_GetStateSnapshot_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/game/engine/v1/engine.proto",
}
